### ISSUE TITLE
The plug-in loading check cannot be completed. Reason: NBM

### ISSUE THREAD

**Issue by korenevskiy** [netbeanslab/nb-sort-line-tools#14] opened 2022-09-14 21:10 UTC
The plug-in loading check cannot be completed. Reason: NBM
C:\Users\koren\AppData\Roaming\NetBeans\14\update\download\org-netbeans-modules-linetools.nbm needs unpack200 to process following entries: 
netbeans/modules/docs/org-netbeans-modules-linetools.jar.pack.gz
netbeans/modules/org-netbeans-modules-linetools.jar.pack.gz

**Comment by markiewb** [comment] 2022-09-14 21:32
Duplicate of #12

**Closed by markiewb** 2022-09-14 21:32 UTC
Labels: duplicate
